## All config here

general:                                                                            # general parameters
  working_folder: ./                                                                # Sets up the working folder directory
  raster_files_folder: S:/PERMEABILITY GLACIAL/AllRasterFiles                       # Folder containing the raster files
  permeability_files_folder: S:/PERMEABILITY GLACIAL/permeability-data              # File containing the PFLOTRAN centroid files
  PFLOTRAN_centroid_file: S:/PERMEABILITY GLACIAL/permeability-data/centroid.dat    # File containing the PFLOTRAN centroid files
  verbose: True                                                                     # increases verbose
  eps: 1E-30                                                                        # Numerical zero value
coord:
  x_local_to_global: 1.52E6
  y_local_to_global: 6.79E6