## All config here

general:                                                                            # general parameters
  working_folder: ./                                                                # Sets up the working folder directory
  raster_files_folder: S:/PERMEABILITY GLACIAL/AllRasterFiles                       # Folder containing the raster files
  permeability_files_folder: S:/PERMEABILITY GLACIAL/permeability-data              # File containing the PFLOTRAN centroid files
  PFLOTRAN_centroid_file: S:/PERMEABILITY GLACIAL/permeability-data/centroid.dat    # File containing the PFLOTRAN centroid files
  verbose: True                                                                     # increases verbose
  eps: 1E-30                                                                        # Numerical zero value
results:
  min_value: 1E-20
  max_value: None
coord:
  x_local_to_global: 1.52E6
  y_local_to_global: 6.79E6
structured_list_reader:
  filename: C:\Users\Aitor\PycharmProjects\PyFLOTRAN\templates\interpolate_grains_to_mesh\data\calcite_32
  nx: 400
  ny: 400
  nz: 20
  dx: 2.5E-4
  dy: 2.5E-4
  dz: 3.265E-4
  ox: 0.0
  oy: 0.0
  oz: -2.52E-3
  header_offset: 3
  csv_file: ./grain_3d.csv

open_foam_reader:
  filename: C:\Users\Aitor\PycharmProjects\PyFLOTRAN\templates\interpolate_grains_to_mesh\data\open_foam_file