## All config here

general:                                                                            # general parameters
  working_folder: ./                                                                # Sets up the working folder directory
  pressure_raster_folder: G:/Mi unidad/dev/PyFLOTRAN/templates/interpolate_top_BC/data/200221_hhem_cal22_noditches_rcp45_min_r1_export_velocity_val/     # Folder containing the raster files
  verbose: True                                                                     # increases verbose
  eps: 1E-30                                                                        # Numerical zero value
coord:
  x_local_to_global: 1.52E6  # Coordinate change x_local = x_global - x_local_to_global
  y_local_to_global: 6.79E6  # Coordinate change y_local = y_global - y_local_to_global